-- ==============================================================================
-- CALORIQ PRODUCTION DATABASE SCHEMA FOR SUPABASE (POSTGRESQL 15+)
-- Project URL: https://tyojindpzxlpbjogsglv.supabase.co
-- Generated: 2026-09-29T08:57:55.060Z
-- Architecture: Multi-tenant, Multi-device Enclave Sync, Realtime Telemetry, Food Diary
-- ==============================================================================

-- 1. Enable Required Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- TABLE 1: sync_enclaves (Inter-device Enclave Coordination & QR Pairings)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.sync_enclaves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_code TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    last_updated TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    devices JSONB NOT NULL DEFAULT '[]'::jsonb,
    last_mutation JSONB NOT NULL DEFAULT '{"type":"init","details":"Enclave created"}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_sync_enclaves_code ON public.sync_enclaves (sync_code);

-- ==============================================================================
-- TABLE 2: user_profiles (Biometric Targets, Asian Indian BMI, BMR, TDEE)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    sync_code TEXT NOT NULL DEFAULT 'CQ-8420-9173',
    age INT NOT NULL DEFAULT 28,
    sex TEXT NOT NULL DEFAULT 'female' CHECK (sex IN ('female', 'male', 'other')),
    height_cm NUMERIC(5,1) NOT NULL DEFAULT 168.0,
    weight_kg NUMERIC(5,1) NOT NULL DEFAULT 68.0,
    activity_level TEXT NOT NULL DEFAULT 'moderate',
    goal TEXT NOT NULL DEFAULT 'lose' CHECK (goal IN ('lose', 'maintain', 'gain')),
    target_rate_kg_per_week NUMERIC(4,2) NOT NULL DEFAULT 0.50,
    bmr INT NOT NULL DEFAULT 1419,
    tdee INT NOT NULL DEFAULT 2200,
    daily_calorie_target INT NOT NULL DEFAULT 1650,
    protein_target_g INT NOT NULL DEFAULT 122,
    carbs_target_g INT NOT NULL DEFAULT 173,
    fat_target_g INT NOT NULL DEFAULT 51,
    fiber_target_g INT NOT NULL DEFAULT 28,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_user_profiles_sync UNIQUE (sync_code)
);

CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON public.user_profiles (user_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_sync_code ON public.user_profiles (sync_code);

-- ==============================================================================
-- TABLE 3: food_entries (Daily Nutrition Log, Spreadsheet Diary, Macro Breakdown)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.food_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    sync_code TEXT NOT NULL DEFAULT 'CQ-8420-9173',
    device_id TEXT,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    time TEXT NOT NULL DEFAULT to_char(timezone('utc'::text, now()), 'HH12:MI AM'),
    meal_type TEXT NOT NULL CHECK (meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')),
    food_name TEXT NOT NULL,
    quantity NUMERIC(8,2) NOT NULL DEFAULT 100,
    quantity_unit TEXT NOT NULL DEFAULT 'g',
    calories NUMERIC(8,2) NOT NULL DEFAULT 0,
    protein NUMERIC(8,2) NOT NULL DEFAULT 0,
    carbs NUMERIC(8,2) NOT NULL DEFAULT 0,
    fat NUMERIC(8,2) NOT NULL DEFAULT 0,
    fiber NUMERIC(8,2) NOT NULL DEFAULT 0,
    sugar NUMERIC(8,2) NOT NULL DEFAULT 0,
    sodium NUMERIC(8,2) NOT NULL DEFAULT 0,
    source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'ai', 'catalog', 'voice')),
    confidence NUMERIC(4,3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_food_entries_sync_date ON public.food_entries (sync_code, date);
CREATE INDEX IF NOT EXISTS idx_food_entries_user_date ON public.food_entries (user_id, date);
CREATE INDEX IF NOT EXISTS idx_food_entries_created_at ON public.food_entries (created_at DESC);

-- ==============================================================================
-- TABLE 4: weight_logs (Weight History & Asian Indian BMI Progression)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.weight_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    sync_code TEXT NOT NULL DEFAULT 'CQ-8420-9173',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    weight_kg NUMERIC(5,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_weight_logs_sync_date ON public.weight_logs (sync_code, date DESC);
CREATE INDEX IF NOT EXISTS idx_weight_logs_user_date ON public.weight_logs (user_id, date DESC);

-- ==============================================================================
-- TABLE 5: trackers_state (Water Hydration, Sleep Debt, Handwash, Wearables)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.trackers_state (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sync_code TEXT NOT NULL DEFAULT 'CQ-8420-9173',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    water_current_ml INT NOT NULL DEFAULT 0,
    water_target_ml INT NOT NULL DEFAULT 3000,
    water_hourly_log JSONB NOT NULL DEFAULT '[]'::jsonb,
    sleep_duration_hours NUMERIC(4,2) NOT NULL DEFAULT 0,
    sleep_target_hours NUMERIC(4,2) NOT NULL DEFAULT 8.0,
    sleep_quality TEXT NOT NULL DEFAULT 'None',
    sleep_debt_minutes INT NOT NULL DEFAULT 0,
    handwash_count_today INT NOT NULL DEFAULT 0,
    handwash_target_count INT NOT NULL DEFAULT 6,
    handwash_streak_days INT NOT NULL DEFAULT 0,
    fitbit_connected BOOLEAN NOT NULL DEFAULT false,
    fitbit_device TEXT NOT NULL DEFAULT 'None',
    wearables_steps INT NOT NULL DEFAULT 0,
    wearables_active_minutes INT NOT NULL DEFAULT 0,
    wearables_heart_rate INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_trackers_sync_date UNIQUE (sync_code, date)
);

CREATE INDEX IF NOT EXISTS idx_trackers_state_sync_date ON public.trackers_state (sync_code, date DESC);

-- ==============================================================================
-- TABLE 6: health_connect_telemetry (Steps, Active Energy, Basal Burn, Audit Logs)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.health_connect_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_code TEXT NOT NULL DEFAULT 'CQ-8420-9173',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    steps INT NOT NULL DEFAULT 0,
    active_calories INT NOT NULL DEFAULT 0,
    basal_calories INT NOT NULL DEFAULT 1419,
    total_calories INT NOT NULL DEFAULT 1419,
    nutrition_records_count INT NOT NULL DEFAULT 0,
    is_estimated BOOLEAN NOT NULL DEFAULT true,
    hourly_data JSONB NOT NULL DEFAULT '[]'::jsonb,
    sync_audit_log JSONB NOT NULL DEFAULT '[]'::jsonb,
    last_synced_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_health_connect_sync_date UNIQUE (sync_code, date)
);

CREATE INDEX IF NOT EXISTS idx_health_connect_sync_date ON public.health_connect_telemetry (sync_code, date DESC);

-- ==============================================================================
-- TABLE 7: indian_food_catalog (Authentic Indian Serving Sizes & Macronutrients)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.indian_food_catalog (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    estimated_grams NUMERIC(8,2) NOT NULL,
    serving_unit TEXT NOT NULL,
    category TEXT NOT NULL,
    calories NUMERIC(8,2) NOT NULL,
    protein NUMERIC(8,2) NOT NULL,
    carbs NUMERIC(8,2) NOT NULL,
    fat NUMERIC(8,2) NOT NULL,
    fiber NUMERIC(8,2) NOT NULL DEFAULT 0,
    sugar NUMERIC(8,2) NOT NULL DEFAULT 0,
    sodium NUMERIC(8,2) NOT NULL DEFAULT 0,
    confidence NUMERIC(4,3) NOT NULL DEFAULT 0.95,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_indian_food_category ON public.indian_food_catalog (category);
CREATE INDEX IF NOT EXISTS idx_indian_food_name ON public.indian_food_catalog (name);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE public.sync_enclaves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.food_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weight_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trackers_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_connect_telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.indian_food_catalog ENABLE ROW LEVEL SECURITY;

-- 1. sync_enclaves Policies
CREATE POLICY "Allow public read-write for active sync enclaves" 
ON public.sync_enclaves FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- 2. user_profiles Policies
CREATE POLICY "Allow public read-write user profiles by sync_code or auth" 
ON public.user_profiles FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- 3. food_entries Policies
CREATE POLICY "Allow public read-write food entries by sync_code or auth" 
ON public.food_entries FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- 4. weight_logs Policies
CREATE POLICY "Allow public read-write weight logs by sync_code or auth" 
ON public.weight_logs FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- 5. trackers_state Policies
CREATE POLICY "Allow public read-write trackers state by sync_code or auth" 
ON public.trackers_state FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- 6. health_connect_telemetry Policies
CREATE POLICY "Allow public read-write health connect telemetry by sync_code" 
ON public.health_connect_telemetry FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- 7. indian_food_catalog Policies (Publicly readable, service_role writable)
CREATE POLICY "Allow public read access to Indian food catalog" 
ON public.indian_food_catalog FOR SELECT TO anon, authenticated 
USING (true);

CREATE POLICY "Allow service_role write access to Indian food catalog" 
ON public.indian_food_catalog FOR ALL TO service_role 
USING (true) WITH CHECK (true);

-- ==============================================================================
-- PERMISSIONS & ROLES
-- ==============================================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

-- ==============================================================================
-- ENABLE SUPABASE REALTIME REPLICATION FOR INSTANT MULTI-DEVICE SYNC
-- ==============================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END $$;

ALTER PUBLICATION supabase_realtime ADD TABLE public.food_entries;
ALTER PUBLICATION supabase_realtime ADD TABLE public.trackers_state;
ALTER PUBLICATION supabase_realtime ADD TABLE public.sync_enclaves;
ALTER PUBLICATION supabase_realtime ADD TABLE public.user_profiles;
ALTER PUBLICATION supabase_realtime ADD TABLE public.weight_logs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.health_connect_telemetry;

-- ==============================================================================
-- SEED DATA: 250+ AUTHENTIC INDIAN & GLOBAL FOODS WITH AUTHENTIC MACROS
-- ==============================================================================
INSERT INTO public.indian_food_catalog (id, name, estimated_grams, serving_unit, category, calories, protein, carbs, fat, fiber, sugar, sodium, confidence)
VALUES
('roti', 'Whole Wheat Roti / Phulka', 35, 'piece', 'staples', 90, 3, 17.5, 0.8, 2.5, 0.3, 65, 0.97),
('roti_ghee', 'Whole Wheat Roti with Pure Ghee', 40, 'piece', 'staples', 120, 3.1, 17.5, 4.2, 2.5, 0.3, 70, 0.96),
('chapati', 'Homestyle Tawa Chapati', 35, 'piece', 'staples', 92, 3, 17.5, 1.2, 2.5, 0.3, 70, 0.96),
('plain_paratha', 'Plain Layered Tawa Paratha', 65, 'piece', 'staples', 185, 4.2, 25, 7.8, 2.2, 0.5, 95, 0.95),
('aloo_paratha', 'Stuffed Aloo Paratha with Butter', 110, 'piece', 'staples', 260, 5.5, 36, 10.5, 3.8, 1.5, 280, 0.94),
('paneer_paratha', 'Stuffed Paneer Paratha', 120, 'piece', 'staples', 290, 11, 30, 13.5, 2.5, 1.2, 240, 0.94),
('gobi_paratha', 'Stuffed Gobi (Cauliflower) Paratha', 110, 'piece', 'staples', 220, 5, 31, 8.5, 4, 1.8, 260, 0.93),
('mooli_paratha', 'Stuffed Mooli (Radish) Paratha', 110, 'piece', 'staples', 210, 4.8, 30, 8, 3.5, 1.2, 270, 0.93),
('methi_thepla', 'Gujarati Methi Thepla', 45, 'piece', 'staples', 120, 3.5, 16, 4.8, 2, 0.5, 140, 0.95),
('puri', 'Deep-Fried Poori / Puri', 30, 'piece', 'staples', 125, 2.2, 14.5, 6.8, 1.2, 0.2, 65, 0.93),
('butter_naan', 'Butter Tandoori Naan', 90, 'piece', 'staples', 280, 7.5, 42, 9.5, 2, 2, 320, 0.92),
('plain_naan', 'Plain Tandoori Naan', 80, 'piece', 'staples', 240, 7, 42, 4.8, 2, 2, 290, 0.93),
('garlic_naan', 'Garlic Butter Tandoori Naan', 95, 'piece', 'staples', 295, 7.8, 43, 10.5, 2.2, 2, 340, 0.92),
('tandoori_roti', 'Wheat Tandoori Roti (No Butter)', 50, 'piece', 'staples', 130, 4.2, 26, 1, 3.2, 0.4, 95, 0.95),
('missi_roti', 'Rajasthani Missi Roti (Gram Flour)', 55, 'piece', 'staples', 145, 5.8, 22, 3.8, 4.2, 0.8, 160, 0.94),
('bajra_roti', 'Bajra Roti (Pearl Millet)', 60, 'piece', 'staples', 150, 4.5, 28, 2.2, 4.5, 0.4, 70, 0.94),
('jowar_roti', 'Jowar Bhakri / Roti (Sorghum)', 60, 'piece', 'staples', 140, 4.2, 29, 1.5, 4, 0.3, 60, 0.94),
('ragi_roti', 'Ragi Roti (Finger Millet)', 60, 'piece', 'staples', 135, 3.8, 27, 1.2, 5.2, 0.2, 65, 0.94),
('white_rice', 'Steamed White Basmati Rice', 150, 'katori', 'staples', 195, 4, 43, 0.4, 0.6, 0.1, 2, 0.95),
('brown_rice', 'Cooked Brown Basmati Rice', 150, 'katori', 'staples', 166, 3.8, 35, 1.4, 2.6, 0.4, 5, 0.93),
('jeera_rice', 'Jeera Rice with Pure Ghee', 160, 'katori', 'staples', 225, 4.2, 44, 3.8, 1, 0.2, 120, 0.92),
('curd_rice', 'South Indian Curd Rice (Thayir Sadam)', 180, 'katori', 'staples', 210, 5.8, 32, 6.8, 1.2, 3.2, 240, 0.94),
('lemon_rice', 'South Indian Lemon Rice with Peanuts', 160, 'katori', 'staples', 240, 4.8, 38, 8, 2, 0.8, 280, 0.93),
('sambar_rice', 'Bisi Bele Bath / Sambar Rice', 220, 'bowl', 'staples', 290, 8.5, 48, 7.5, 5, 2.5, 380, 0.93),
('khichdi', 'Moong Dal Khichdi (Homestyle)', 220, 'bowl', 'staples', 240, 7.5, 36, 7, 4.5, 1, 280, 0.94),
('veg_khichdi', 'Vegetable Masala Khichdi with Ghee', 240, 'bowl', 'staples', 270, 8.2, 42, 7.8, 5.5, 2, 310, 0.93),
('poha', 'Kanda Poha with Peanuts & Sev', 150, 'katori', 'staples', 220, 5, 34, 7.5, 2.8, 2, 210, 0.95),
('upma', 'Rava Upma with Mixed Vegetables', 150, 'katori', 'staples', 190, 4.5, 30, 6, 2.5, 1.5, 190, 0.94),
('veg_dalia', 'Vegetable Dalia (Broken Wheat Porridge)', 200, 'bowl', 'staples', 175, 6.2, 31, 3.2, 6.5, 1.8, 180, 0.94),
('milk_dalia', 'Sweet Milk Dalia with Almonds', 220, 'bowl', 'staples', 230, 7.8, 38, 5.5, 4.5, 14, 85, 0.92),
('oats_upma', 'Savory Oats Upma with Veggies', 180, 'bowl', 'staples', 160, 6, 26, 3.8, 4.2, 1.2, 175, 0.93),
('quinoa', 'Cooked Quinoa (Plain)', 150, 'katori', 'staples', 180, 6.5, 32, 2.8, 4, 0.8, 8, 0.93),
('dal_tadka', 'Yellow Dal Tadka (Toor / Moong)', 150, 'katori', 'dals', 150, 7.5, 20, 4.5, 4.8, 1.2, 290, 0.95),
('dal_fry', 'Restaurant Style Dal Fry (Butter Tadka)', 160, 'katori', 'dals', 190, 8, 22, 7.8, 5, 1.5, 340, 0.93),
('dal_makhani', 'Punjabi Dal Makhani (Black Urad)', 160, 'katori', 'dals', 260, 8.5, 22, 15, 6.2, 2, 340, 0.94),
('moong_dal', 'Yellow Moong Dal (Light Homestyle)', 150, 'katori', 'dals', 135, 8.2, 19, 2.8, 4.2, 0.8, 240, 0.95),
('masoor_dal', 'Red Masoor Dal Tadka', 150, 'katori', 'dals', 140, 8.5, 20.5, 3, 4.5, 1, 260, 0.94),
('chana_dal', 'Chana Dal Tadka (Bengal Gram)', 150, 'katori', 'dals', 175, 9.2, 24, 4.5, 6, 1.2, 280, 0.93),
('panchmel_dal', 'Rajasthani Panchmel Dal (5 Dal Mix)', 160, 'katori', 'dals', 180, 9.5, 23, 5.5, 6, 1.5, 310, 0.92),
('rajma', 'Punjabi Rajma Masala (Kidney Beans)', 160, 'katori', 'dals', 180, 9, 24, 5, 6.5, 2.2, 310, 0.94),
('rajma_chawal', 'Rajma Chawal Combo Platter', 300, 'plate', 'dals', 420, 14, 68, 8.5, 8, 2.5, 380, 0.95),
('chole', 'Punjabi Chole Masala (Chickpea Curry)', 160, 'katori', 'dals', 210, 8.5, 28, 7, 7, 3, 360, 0.94),
('pindi_chole', 'Rawalpindi Chole (Dry Spiced)', 140, 'katori', 'dals', 195, 8.8, 26, 6.5, 6.8, 2, 340, 0.93),
('chole_bhature', 'Chole Bhature (2 Bhature + Chole)', 320, 'plate', 'dals', 620, 15, 78, 28, 7.5, 4.5, 620, 0.95),
('kala_chana', 'Black Kala Chana Tariwala', 150, 'katori', 'dals', 165, 8.5, 23, 4.2, 7.5, 1.5, 290, 0.93),
('lobia_curry', 'Lobia Masala (Black-Eyed Peas)', 150, 'katori', 'dals', 160, 8.8, 24, 3.8, 6.2, 1.8, 270, 0.92),
('sprouted_moong_curry', 'Sprouted Green Moong Usal / Curry', 150, 'katori', 'dals', 145, 9.5, 21, 3, 6, 1.5, 240, 0.94),
('sambar', 'South Indian Veg Sambar', 160, 'katori', 'dals', 110, 5, 17, 2.5, 4, 3, 320, 0.95),
('tomato_rasam', 'Spicy Tomato Garlic Rasam', 150, 'cup', 'dals', 65, 2, 10, 1.8, 1.5, 3, 280, 0.95),
('kadhi_pakora', 'Punjabi Besan Kadhi with Pakora', 180, 'katori', 'dals', 235, 6.8, 22, 13.5, 3, 3.5, 380, 0.93),
('gujarati_kadhi', 'Gujarati Sweet & Sour Kadhi', 150, 'katori', 'dals', 120, 4.2, 14, 5.2, 0.8, 6.5, 260, 0.93),
('paneer', 'Fresh Paneer Cubes (Cottage Cheese)', 100, 'katori', 'curries', 265, 18.3, 3.4, 20.8, 0, 2.5, 22, 0.96),
('paneer_butter_masala', 'Rich Paneer Butter Masala', 160, 'katori', 'curries', 310, 12, 10, 24, 2, 4, 390, 0.94),
('palak_paneer', 'Palak Paneer (Spinach Cottage Cheese)', 160, 'katori', 'curries', 220, 13, 7, 16, 3.8, 2, 310, 0.94),
('kadai_paneer', 'Kadai Paneer with Bell Peppers', 160, 'katori', 'curries', 250, 12.5, 9, 18, 3, 2.5, 340, 0.93),
('matar_paneer', 'Matar Paneer Curry', 160, 'katori', 'curries', 230, 11.5, 12, 15, 3.5, 3.2, 320, 0.93),
('shahi_paneer', 'Mughlai Shahi Paneer', 160, 'katori', 'curries', 290, 11, 12, 22, 1.5, 5, 360, 0.92),
('paneer_bhurji', 'Paneer Bhurji (Scrambled Cottage Cheese)', 140, 'katori', 'curries', 245, 15.5, 5.5, 18, 1.8, 2, 290, 0.94),
('paneer_tikka', 'Tandoori Paneer Tikka (4 Grilled Cubes)', 150, 'plate', 'curries', 230, 16, 6.5, 15.5, 2, 2.2, 310, 0.94),
('malai_kofta', 'Malai Kofta in Creamy Gravy', 160, 'katori', 'curries', 330, 7.5, 24, 23, 2.8, 5.5, 410, 0.91),
('aloo_gobi', 'Homestyle Aloo Gobi Matar', 140, 'katori', 'curries', 145, 3.5, 18, 6.5, 3.5, 2.5, 220, 0.94),
('jeera_aloo', 'Dry Jeera Aloo Sabzi', 130, 'katori', 'curries', 160, 2.8, 24, 6, 3, 1.2, 240, 0.93),
('dum_aloo', 'Kashmiri Dum Aloo in Spiced Gravy', 150, 'katori', 'curries', 210, 3.8, 26, 10.5, 3.5, 3, 320, 0.92),
('bhindi_masala', 'Bhindi Masala (Okra Sabzi)', 120, 'katori', 'curries', 120, 2.5, 12, 7, 4, 2.2, 180, 0.94),
('baingan_bharta', 'Smoked Baingan Bharta (Roasted Eggplant)', 140, 'katori', 'curries', 125, 2.8, 13, 7, 5, 4, 220, 0.93),
('lauki_sabzi', 'Lauki / Bottle Gourd Homestyle Sabzi', 140, 'katori', 'curries', 85, 1.8, 9, 4.8, 3, 2.5, 160, 0.95),
('lauki_chana_dal', 'Lauki Chana Dal Curry', 150, 'katori', 'curries', 115, 4.8, 15, 4.2, 4.5, 2, 210, 0.94),
('sarson_saag', 'Sarson Ka Saag with White Butter', 160, 'katori', 'curries', 180, 5, 14, 11.5, 5.8, 2, 310, 0.93),
('mix_veg', 'Mixed Vegetable Curry (Carrots, Peas, Beans)', 140, 'katori', 'curries', 130, 3, 15, 6, 4.2, 3, 210, 0.93),
('soya_chunks_curry', 'Soya Chunks Curry (High Protein Meal Maker)', 150, 'katori', 'curries', 160, 16.5, 12, 5, 4.8, 2, 280, 0.95),
('soya_chaap_curry', 'Tandoori Soya Chaap Gravy', 160, 'katori', 'curries', 280, 14, 24, 14, 4, 3, 380, 0.92),
('mushroom_masala', 'Mushroom Masala Curry', 150, 'katori', 'curries', 135, 4.5, 11, 8, 3.2, 3, 260, 0.93),
('tofu_stir_fry', 'Tofu & Mixed Veggies Stir-Fry', 160, 'bowl', 'curries', 155, 13.5, 8, 8, 3.5, 2.5, 290, 0.94),
('idli', 'Steamed Rice & Urad Idli (1 pc)', 50, 'piece', 'south_indian', 65, 2, 13.5, 0.3, 1, 0.2, 80, 0.97),
('idli_sambar', 'Steamed Idlis with Sambar (2 idlis + sambar)', 180, 'plate', 'south_indian', 180, 6.5, 34, 2, 3.5, 2, 280, 0.96),
('plain_dosa', 'Crispy Plain Dosa', 120, 'piece', 'south_indian', 160, 4, 28, 3.5, 1.8, 0.5, 210, 0.95),
('masala_dosa', 'Masala Dosa with Potato Filling', 180, 'piece', 'south_indian', 290, 6, 42, 10.5, 3, 2, 360, 0.95),
('mysore_masala_dosa', 'Mysore Masala Dosa with Red Garlic Chutney', 200, 'piece', 'south_indian', 340, 7, 46, 14, 3.5, 2.2, 420, 0.93),
('rava_dosa', 'Crispy Rava Onion Dosa', 150, 'piece', 'south_indian', 260, 5.2, 38, 9.5, 2, 1.5, 280, 0.93),
('ragi_dosa', 'Healthy Ragi Dosa (Finger Millet)', 130, 'piece', 'south_indian', 195, 5, 32, 5, 4.5, 0.5, 220, 0.94),
('medu_vada', 'Crispy Medu Vada (1 pc)', 60, 'piece', 'south_indian', 165, 4, 15, 10, 2.5, 0.3, 180, 0.94),
('sambar_vada', 'Sambar Vada (2 Vadas Soaked in Sambar)', 220, 'bowl', 'south_indian', 330, 9.5, 36, 17, 5.5, 3, 490, 0.93),
('onion_uttapam', 'Onion Uttapam with Coriander', 180, 'plate', 'south_indian', 270, 6.5, 44, 7.5, 3, 3, 290, 0.94),
('appam', 'Kerala Soft Appam (2 pcs)', 120, 'plate', 'south_indian', 180, 3.2, 38, 1.5, 1, 2.5, 110, 0.92),
('coconut_chutney', 'Fresh White Coconut Chutney', 30, 'tbsp', 'south_indian', 75, 1, 2.5, 7, 1.5, 1, 95, 0.95),
('tomato_chutney', 'Spicy Red Tomato Onion Chutney', 30, 'tbsp', 'south_indian', 45, 0.8, 5, 2.5, 1, 2.5, 110, 0.95),
('boiled_egg', 'Whole Boiled Egg', 50, 'piece', 'non_veg', 78, 6.3, 0.6, 5.3, 0, 0.6, 62, 0.98),
('egg_white', 'Boiled Egg White Only', 33, 'piece', 'non_veg', 17, 3.6, 0.2, 0.1, 0, 0.2, 55, 0.99),
('scrambled_eggs', 'Scrambled Eggs (2 Whole Eggs)', 120, 'plate', 'non_veg', 182, 13, 1.8, 13.6, 0, 1.5, 170, 0.96),
('masala_omelette', 'Indian Masala Omelette (2 Eggs with Onion & Chili)', 130, 'plate', 'non_veg', 195, 13.5, 3.5, 14, 0.8, 1.5, 240, 0.96),
('egg_bhurji', 'Street Style Egg Bhurji (2 Eggs)', 130, 'plate', 'non_veg', 210, 14, 4.5, 15, 1.2, 1.8, 260, 0.95),
('egg_curry', 'Homestyle Egg Curry (2 Boiled Eggs in Gravy)', 180, 'plate', 'non_veg', 240, 14.5, 6, 17, 1.5, 2, 320, 0.95),
('chicken_breast', 'Grilled Chicken Breast (Skinless)', 150, 'piece', 'non_veg', 248, 46.5, 0, 5.4, 0, 0, 112, 0.97),
('chicken_biryani', 'Dum Chicken Biryani (Basmati Rice & Chicken)', 350, 'plate', 'non_veg', 540, 32, 65, 16, 3, 2, 480, 0.96),
('mutton_biryani', 'Hyderabadi Dum Mutton Biryani', 350, 'plate', 'non_veg', 620, 34, 64, 24, 2.8, 2.2, 520, 0.94),
('chicken_curry', 'Homestyle Tariwala Chicken Curry', 170, 'katori', 'non_veg', 240, 28, 4, 12, 1.5, 1.5, 360, 0.94),
('butter_chicken', 'Murgh Makhani (Butter Chicken)', 170, 'katori', 'non_veg', 340, 25, 8, 22, 1.8, 4.5, 420, 0.93),
('chicken_tikka_masala', 'Chicken Tikka Masala Gravy', 170, 'katori', 'non_veg', 310, 26, 9, 18.5, 2, 4, 410, 0.93),
('kadai_chicken', 'Kadai Chicken with Bell Peppers', 170, 'katori', 'non_veg', 270, 29, 6, 14, 2, 2.5, 370, 0.93),
('tandoori_chicken', 'Tandoori Chicken (1 Leg / Breast Piece)', 180, 'piece', 'non_veg', 260, 36, 3, 11, 1, 1, 440, 0.95),
('chicken_tikka', 'Tandoori Chicken Tikka (4 Boneless Pcs)', 150, 'plate', 'non_veg', 220, 34, 3, 7.5, 1, 1, 380, 0.95),
('chicken_seekh_kebab', 'Grilled Chicken Seekh Kebab (2 skewers)', 120, 'plate', 'non_veg', 230, 28, 4, 11, 1.2, 1.2, 390, 0.94),
('mutton_curry', 'Homestyle Mutton Curry', 170, 'katori', 'non_veg', 330, 26, 4, 23, 1, 1, 390, 0.92),
('mutton_rogan_josh', 'Kashmiri Mutton Rogan Josh', 170, 'katori', 'non_veg', 350, 27, 5, 24.5, 1.5, 1.5, 420, 0.92),
('keema_matar', 'Minced Mutton Keema Matar', 160, 'katori', 'non_veg', 310, 25, 8, 20, 2.5, 2, 380, 0.93),
('fish_curry', 'Coastal Indian Fish Curry (Mustard / Coconut)', 170, 'katori', 'non_veg', 210, 24, 5, 10.5, 1.2, 1.5, 340, 0.93),
('fish_fry', 'Rawa Masala Pan-Fried Fish', 140, 'piece', 'non_veg', 230, 26, 8, 10, 0.8, 0.5, 360, 0.93),
('prawns_curry', 'Prawns Masala Curry', 150, 'katori', 'non_veg', 195, 22, 6, 9, 1.5, 2, 410, 0.92),
('salmon', 'Pan-Seared / Baked Salmon Fillet', 170, 'piece', 'non_veg', 354, 37.8, 0, 21.8, 0, 0, 104, 0.96),
('samosa', 'Punjabi Aloo Samosa (1 pc)', 80, 'piece', 'snacks', 260, 4, 30, 14, 2.5, 1.5, 340, 0.96),
('pani_puri', 'Pani Puri / Golgappe (6 pcs with Teekha/Meetha Pani)', 150, 'plate', 'snacks', 190, 3.5, 32, 5, 2.5, 4, 480, 0.94),
('sev_puri', 'Sev Puri (6 pcs Loaded with Potatoes & Sev)', 140, 'plate', 'snacks', 260, 5, 38, 10.5, 3, 5.5, 390, 0.93),
('dahi_puri', 'Dahi Puri / SPDP (6 pcs with Sweet Curd)', 180, 'plate', 'snacks', 310, 6.8, 44, 12, 2.8, 11, 380, 0.93),
('bhel_puri', 'Mumbai Bhel Puri with Tangy Chutneys', 140, 'plate', 'snacks', 220, 5, 38, 5.5, 3.2, 6, 340, 0.94),
('pav_bhaji', 'Mumbai Pav Bhaji (2 Buttered Pavs + Bhaji)', 280, 'plate', 'snacks', 480, 9.5, 62, 22, 6.5, 5, 620, 0.95),
('vada_pav', 'Mumbai Vada Pav with Lasun Chutney', 120, 'piece', 'snacks', 290, 6.2, 42, 11, 3, 2.5, 380, 0.95),
('dahi_vada', 'Dahi Vada / Dahi Bhalla (2 pcs)', 180, 'plate', 'snacks', 240, 8, 30, 9.5, 2.5, 9, 340, 0.94),
('aloo_tikki', 'Crispy Aloo Tikki with Chole & Curd', 200, 'plate', 'snacks', 320, 7, 46, 12, 5, 6, 440, 0.93),
('moong_dal_chilla', 'Moong Dal Chilla / Cheela with Paneer', 90, 'piece', 'snacks', 160, 8.5, 18, 6, 3, 1.2, 180, 0.95),
('besan_chilla', 'Besan Chilla (Gram Flour Pancake)', 80, 'piece', 'snacks', 140, 6.8, 16, 5.2, 3.2, 1.5, 190, 0.95),
('veg_pakora', 'Mixed Vegetable Pakoras (4 pcs)', 100, 'plate', 'snacks', 275, 5.2, 26, 17, 3.5, 2, 310, 0.93),
('dhokla', 'Steamed Khaman Dhokla (2 pcs with Mustard Tadka)', 80, 'piece', 'snacks', 140, 4.5, 22, 3.5, 2, 3.5, 220, 0.95),
('khandvi', 'Gujarati Khandvi Rolls (4 rolls)', 100, 'plate', 'snacks', 140, 5.5, 16, 6, 2.2, 2, 210, 0.93),
('roasted_makhana', 'Roasted Makhana / Foxnuts (1 bowl)', 35, 'bowl', 'snacks', 125, 3.5, 24, 1.5, 4.2, 0.2, 95, 0.96),
('roasted_chana', 'Roasted Bengal Gram / Bhuna Chana', 40, 'bowl', 'snacks', 150, 8, 23, 2.5, 6.8, 1, 45, 0.96),
('masala_papad', 'Roasted Masala Papad (Onion & Tomato)', 35, 'piece', 'snacks', 65, 2.8, 11, 0.8, 1.8, 1.2, 240, 0.95),
('curd', 'Fresh Dahi / Curd (Whole Milk)', 150, 'katori', 'dairy_protein', 110, 5.2, 7, 6.5, 0, 7, 65, 0.97),
('toned_curd', 'Low-Fat / Toned Dahi', 150, 'katori', 'dairy_protein', 75, 5.5, 7.5, 2.2, 0, 7.5, 70, 0.96),
('greek_yogurt', 'Plain Greek Yogurt (Non-Fat)', 170, 'cup', 'dairy_protein', 100, 17.3, 6.1, 0.7, 0, 6.1, 60, 0.97),
('cow_milk', 'Fresh Cow Milk (Boiled, 1 glass)', 250, 'glass', 'dairy_protein', 155, 8, 12, 8.5, 0, 12, 110, 0.96),
('toned_milk', 'Toned Milk (3% Fat, 1 glass)', 250, 'glass', 'dairy_protein', 120, 7.8, 12.5, 4.5, 0, 12.5, 115, 0.96),
('skimmed_milk', 'Double Toned / Skimmed Milk (1 glass)', 250, 'glass', 'dairy_protein', 85, 8.2, 12.5, 0.5, 0, 12.5, 120, 0.96),
('soy_milk', 'Unsweetened Soy Milk', 250, 'glass', 'dairy_protein', 90, 8, 4, 4.5, 1.5, 1, 95, 0.95),
('almond_milk', 'Unsweetened Almond Milk', 250, 'glass', 'dairy_protein', 35, 1.2, 1, 2.8, 0.8, 0.2, 140, 0.95),
('whey_isolate', 'Whey Protein Isolate (1 scoop)', 30, 'scoop', 'dairy_protein', 115, 27, 1, 0.5, 0, 0.5, 120, 0.98),
('whey_concentrate', 'Whey Protein Concentrate (1 scoop)', 33, 'scoop', 'dairy_protein', 130, 24, 3, 2.2, 0.5, 1.5, 140, 0.97),
('plant_protein', 'Plant Protein Powder (Pea & Brown Rice, 1 scoop)', 35, 'scoop', 'dairy_protein', 135, 25, 3.5, 2.5, 2, 0.5, 190, 0.96),
('peanut_butter', 'Natural Peanut Butter (No Added Sugar)', 16, 'tbsp', 'dairy_protein', 95, 4, 3.2, 8, 1.2, 0.8, 5, 0.96),
('chia_seeds', 'Chia Seeds (Raw / Soaked)', 12, 'tbsp', 'dairy_protein', 58, 2, 5, 3.7, 4.1, 0, 2, 0.97),
('flax_seeds', 'Flax Seeds (Roasted / Ground)', 10, 'tbsp', 'dairy_protein', 55, 1.9, 3, 4.2, 2.8, 0.1, 3, 0.97),
('soaked_almonds', 'Soaked Raw Almonds (5 almonds)', 6, 'piece', 'dairy_protein', 36, 1.3, 1.2, 3.1, 0.7, 0.3, 0, 0.98),
('walnuts', 'Raw Walnuts (4 halves)', 12, 'piece', 'dairy_protein', 78, 1.8, 1.6, 7.8, 0.8, 0.3, 0, 0.97),
('apple', 'Fresh Gala / Fuji Apple', 182, 'piece', 'fruits_veg', 95, 0.5, 25.1, 0.3, 4.4, 18.9, 2, 0.98),
('banana', 'Fresh Banana (Robusta / Yelakki)', 118, 'piece', 'fruits_veg', 105, 1.3, 27, 0.3, 3.1, 14.4, 1, 0.98),
('orange', 'Fresh Sweet Orange / Mosambi', 131, 'piece', 'fruits_veg', 62, 1.2, 15.4, 0.2, 3.1, 12.2, 0, 0.97),
('mango', 'Fresh Mango Slices (Alphonso / Kesar)', 165, 'katori', 'fruits_veg', 110, 1.4, 28, 0.6, 2.6, 24, 2, 0.95),
('papaya', 'Fresh Papaya Cubes', 180, 'bowl', 'fruits_veg', 75, 0.9, 19, 0.4, 3.1, 14, 5, 0.96),
('watermelon', 'Fresh Watermelon Chunks', 200, 'bowl', 'fruits_veg', 60, 1.2, 15, 0.3, 0.8, 12.4, 2, 0.97),
('pineapple', 'Fresh Pineapple Slices', 165, 'bowl', 'fruits_veg', 82, 0.9, 21.6, 0.2, 2.3, 16.3, 2, 0.95),
('guava', 'Fresh Guava (Amrood)', 120, 'piece', 'fruits_veg', 68, 2.6, 14.3, 1, 5.4, 8.9, 2, 0.96),
('pomegranate', 'Pomegranate Arils / Seeds (Anar)', 120, 'katori', 'fruits_veg', 95, 2, 22, 1.4, 4.5, 16, 3, 0.96),
('grapes', 'Fresh Green / Black Grapes', 150, 'cup', 'fruits_veg', 104, 1.1, 27, 0.2, 1.4, 23, 3, 0.95),
('chikoo', 'Fresh Chikoo / Sapodilla', 80, 'piece', 'fruits_veg', 65, 0.4, 16, 0.9, 4.3, 11.5, 9, 0.94),
('avocado', 'Fresh Hass Avocado (Half)', 68, 'piece', 'fruits_veg', 114, 1.4, 6, 10.5, 4.6, 0.4, 5, 0.96),
('kachumber_salad', 'Kachumber Salad (Cucumber, Onion, Tomato)', 150, 'bowl', 'fruits_veg', 45, 1.8, 9.5, 0.5, 2.8, 4.5, 95, 0.96),
('cucumber_slices', 'Fresh Sliced Cucumber with Salt & Pepper', 120, 'plate', 'fruits_veg', 18, 0.8, 4, 0.1, 1, 2, 80, 0.98),
('sweet_potato', 'Boiled Sweet Potato (Shakarkandi Chaat)', 150, 'bowl', 'fruits_veg', 130, 2.4, 30, 0.2, 4.5, 6.5, 85, 0.95),
('masala_chai', 'Masala Chai with Whole Milk & Sugar', 200, 'cup', 'beverages', 120, 3.5, 18, 4, 0.2, 16, 45, 0.96),
('chai_no_sugar', 'Masala Chai (Toned Milk, No Sugar)', 200, 'cup', 'beverages', 65, 3.5, 6, 2.5, 0.2, 5.5, 45, 0.96),
('green_tea', 'Plain Green Tea (Unsweetened)', 200, 'cup', 'beverages', 2, 0.2, 0, 0, 0, 0, 2, 0.99),
('black_coffee', 'Black Coffee / Americano (Unsweetened)', 240, 'cup', 'beverages', 2, 0.3, 0, 0, 0, 0, 5, 0.99),
('filter_coffee', 'South Indian Filter Coffee with Milk', 150, 'tumbler', 'beverages', 110, 3.2, 14.5, 4.2, 0, 12, 40, 0.95),
('chaas', 'Spiced Buttermilk / Chaas', 250, 'glass', 'beverages', 55, 3.2, 4.8, 2.2, 0.1, 4.8, 140, 0.96),
('sweet_lassi', 'Sweet Punjabi Lassi (with Malai)', 250, 'glass', 'beverages', 240, 7, 36, 7.5, 0, 32, 95, 0.94),
('mango_lassi', 'Thick Mango Lassi', 250, 'glass', 'beverages', 260, 6.5, 42, 7, 1.2, 38, 90, 0.93),
('coconut_water', 'Fresh Tender Coconut Water (Nariyal Pani)', 240, 'glass', 'beverages', 45, 1.7, 9, 0.5, 2.6, 6, 60, 0.98),
('nimbu_pani', 'Nimbu Shikanji (Sweet & Salty Lemonade)', 250, 'glass', 'beverages', 75, 0.5, 18, 0.1, 0.2, 16.5, 180, 0.96),
('sugarcane_juice', 'Fresh Sugarcane Juice with Ginger & Mint', 250, 'glass', 'beverages', 180, 0.8, 45, 0.2, 0.5, 42, 25, 0.94),
('sattu_drink', 'Bihari Sattu Sharbat (Savory with Jeera & Salt)', 250, 'glass', 'beverages', 160, 9.5, 24, 2.8, 6.2, 0.8, 220, 0.95),
('haldi_doodh', 'Golden Turmeric Milk with Black Pepper', 200, 'glass', 'beverages', 140, 6.5, 12, 7, 0.5, 10, 90, 0.95),
('gulab_jamun', 'Gulab Jamun with Sugar Syrup (1 pc)', 50, 'piece', 'sweets', 175, 2.5, 28, 6.2, 0.2, 24, 45, 0.96),
('rasgulla', 'Bengali Spongy Rasgulla (1 pc)', 50, 'piece', 'sweets', 125, 3, 25, 1.5, 0, 22, 25, 0.95),
('rasmalai', 'Rasmalai with Saffron Milk Rabdi (1 pc)', 65, 'piece', 'sweets', 180, 4.5, 22, 8.5, 0.2, 18, 55, 0.94),
('kaju_katli', 'Silver Leaf Kaju Katli (1 diamond pc)', 20, 'piece', 'sweets', 85, 2.2, 10.5, 4.2, 0.5, 8, 5, 0.96),
('motichoor_ladoo', 'Motichoor Ladoo with Pure Ghee (1 pc)', 45, 'piece', 'sweets', 190, 2.8, 28, 7.5, 0.8, 22, 35, 0.95),
('besan_ladoo', 'Besan Ladoo with Roasted Ghee (1 pc)', 45, 'piece', 'sweets', 210, 4.2, 26, 10.5, 1.8, 18, 20, 0.95),
('gajar_halwa', 'Gajar Ka Halwa with Khoya & Dry Fruits', 120, 'katori', 'sweets', 290, 5.5, 38, 13.5, 3.2, 30, 75, 0.93),
('moong_dal_halwa', 'Shahi Moong Dal Halwa with Pure Ghee', 100, 'katori', 'sweets', 380, 7, 42, 21, 2.5, 34, 40, 0.92),
('kheer', 'Traditional Rice Kheer with Kesar & Elaichi', 150, 'katori', 'sweets', 220, 5.8, 34, 7.2, 0.5, 24, 65, 0.94),
('jalebi', 'Crispy Desi Ghee Jalebi (2 pcs)', 60, 'piece', 'sweets', 220, 1.8, 42, 5.5, 0.2, 36, 30, 0.94),
('mishti_doi', 'Bengali Baked Sweet Curd (Mishti Doi)', 120, 'katori', 'sweets', 180, 4.5, 26, 6.8, 0, 24, 50, 0.94),
('wheat_bread', 'Whole Wheat Bread (1 slice)', 35, 'slice', 'global', 88, 4, 14.5, 1.2, 2.1, 1.5, 140, 0.97),
('multigrain_bread', 'Multigrain Seeded Bread (1 slice)', 38, 'slice', 'global', 95, 4.5, 15, 1.8, 2.8, 1.2, 135, 0.97),
('oatmeal', 'Cooked Rolled Oatmeal (with water)', 234, 'bowl', 'global', 158, 6, 28, 3.2, 4, 1.1, 115, 0.96),
('cheese_pizza', 'Classic Margherita / Cheese Pizza (1 slice)', 107, 'slice', 'global', 285, 12.2, 35.7, 10.4, 2.5, 3.8, 640, 0.95),
('veg_burger', 'Vegetable Burger with Whole Wheat Bun', 180, 'piece', 'global', 360, 9.5, 52, 13, 4.8, 6.5, 580, 0.93),
('french_fries', 'Crispy French Fries (Medium portion)', 117, 'plate', 'global', 365, 4, 48, 17.5, 4.2, 0.5, 280, 0.95),
('pasta_red', 'Penne Pasta in Arrabbiata Red Sauce', 200, 'bowl', 'global', 240, 7.8, 42, 4.5, 3.8, 5, 420, 0.93),
('pasta_white', 'Fettuccine Pasta in Alfredo White Sauce', 220, 'bowl', 'global', 380, 9.5, 44, 19, 2.5, 3.5, 510, 0.92),
('veg_noodles', 'Vegetable Hakka Noodles', 200, 'bowl', 'global', 280, 6.5, 46, 8, 3.5, 2.5, 490, 0.93),
('veg_fried_rice', 'Vegetable Fried Rice', 200, 'bowl', 'global', 290, 5.8, 48, 8.5, 2.8, 2, 460, 0.93),
('chicken_fried_rice', 'Chicken Fried Rice with Egg & Veggies', 220, 'bowl', 'global', 360, 18, 48, 10.5, 2.5, 2, 510, 0.94),
('steamed_veg_momos', 'Steamed Vegetable Momos (6 pcs with Chutney)', 150, 'plate', 'global', 210, 6, 38, 3.8, 3, 2, 380, 0.95),
('steamed_chicken_momos', 'Steamed Chicken Momos (6 pcs with Chutney)', 160, 'plate', 'global', 250, 16.5, 36, 4.5, 2, 1.5, 410, 0.95),
('litti_chokha', 'Bihari Litti Chokha (2 Littis with Baingan Chokha & Ghee)', 250, 'plate', 'staples', 420, 12, 68, 12, 8.5, 3, 460, 0.94),
('misal_pav', 'Kolhapuri Misal Pav (Sprouts Rassa with 2 Pavs & Farsan)', 300, 'plate', 'snacks', 480, 15, 64, 18, 8, 4.5, 680, 0.94),
('ragda_pattice', 'Ragda Pattice (2 Potato Patties with White Peas Curry)', 220, 'plate', 'snacks', 340, 8.5, 52, 11, 6.5, 5, 480, 0.93),
('kachori', 'Khasta Dal / Pyaaz Kachori (1 pc)', 85, 'piece', 'snacks', 290, 5.5, 32, 16, 3, 1.5, 360, 0.94),
('bedmi_poori', 'Bedmi Poori with Aloo Sabzi (2 Urad Pooris)', 220, 'plate', 'staples', 480, 10.5, 54, 24, 5.5, 2, 510, 0.93),
('pesarattu', 'Andhra Green Moong Pesarattu (with Upma & Ginger Chutney)', 140, 'piece', 'south_indian', 210, 9.5, 30, 6, 4.5, 1, 240, 0.94),
('akki_rotti', 'Karnataka Akki Rotti (Rice Flour with Dill & Coconut)', 80, 'piece', 'south_indian', 160, 3.2, 30, 3.5, 2, 0.5, 180, 0.93),
('neer_dosa', 'Mangalorean Neer Dosa (2 soft dosas)', 100, 'plate', 'south_indian', 140, 2.8, 30, 1, 1, 0.2, 110, 0.94),
('chicken_kathi_roll', 'Kolkata Chicken Kathi Roll with Flaky Paratha', 200, 'roll', 'non_veg', 420, 26, 42, 16, 2.5, 2.5, 540, 0.95),
('egg_roll', 'Kolkata Double Egg Kathi Roll', 180, 'roll', 'non_veg', 380, 16.5, 40, 17.5, 2, 2, 480, 0.95),
('paneer_roll', 'Paneer Tikka Kathi Roll', 200, 'roll', 'curries', 390, 18, 44, 16, 3, 3, 490, 0.94),
('mutton_korma', 'Shahi Awadhi Mutton Korma', 170, 'katori', 'non_veg', 360, 27, 6, 26, 1.2, 2, 410, 0.93),
('surmai_fry', 'Surmai / Kingfish Tawa Fry', 150, 'piece', 'non_veg', 260, 30, 5, 13, 0.8, 0.2, 380, 0.94),
('pomfret_tandoori', 'Whole Tandoori Pomfret Fish', 220, 'piece', 'non_veg', 270, 36, 3, 12, 1, 0.5, 410, 0.95),
('rohu_fish_curry', 'Bengali Macher Jhol (Rohu with Potato & Cauliflower)', 180, 'katori', 'non_veg', 195, 22, 7, 8.5, 1.5, 1, 320, 0.94),
('hilsa_mustard', 'Shorshe Ilish (Hilsa in Mustard Gravy)', 150, 'piece', 'non_veg', 310, 21, 4, 23, 1.2, 0.5, 340, 0.93),
('crab_masala', 'Spicy Coastal Crab Masala Curry', 200, 'plate', 'non_veg', 220, 26, 6, 10, 1.5, 1.5, 460, 0.92),
('pork_vindaloo', 'Goan Pork Vindaloo with Vinegar', 160, 'katori', 'non_veg', 340, 25, 5, 24, 1, 1.5, 420, 0.92),
('thukpa', 'Himalayan Chicken Thukpa Noodle Soup', 300, 'bowl', 'non_veg', 260, 18, 36, 5.5, 3.5, 2.5, 560, 0.94),
('undhiyu', 'Gujarati Surti Undhiyu (Mixed Vegetables & Muthia)', 160, 'katori', 'curries', 260, 6, 28, 14, 6.5, 4.5, 330, 0.93),
('shrikhand', 'Kesar Pista Shrikhand (Hung Curd Sweet)', 100, 'katori', 'sweets', 260, 7.5, 32, 11.5, 0.5, 30, 40, 0.94),
('kulfi', 'Traditional Malai Pista Kulfi on Stick', 70, 'piece', 'sweets', 190, 4.5, 22, 9.5, 0.5, 20, 55, 0.94),
('rabdi', 'Rich Lachha Rabdi with Dry Fruits', 100, 'katori', 'sweets', 280, 7, 28, 15, 0.3, 24, 65, 0.93),
('malpua', 'Desi Ghee Malpua with Rabdi (1 pc)', 75, 'piece', 'sweets', 260, 4, 36, 11, 0.5, 28, 45, 0.93),
('mysore_pak', 'Ghee Mysore Pak (1 piece)', 40, 'piece', 'sweets', 210, 2.5, 22, 12.5, 0.8, 18, 15, 0.94),
('kalakand', 'Alwar Style Soft Paneer Kalakand (1 pc)', 40, 'piece', 'sweets', 140, 4.8, 16, 6.5, 0.2, 14, 35, 0.94),
('peda', 'Mathura Peda / Doodh Peda (1 pc)', 30, 'piece', 'sweets', 120, 3, 18, 4.2, 0.1, 16, 25, 0.95),
('ghevar', 'Rajasthani Malai Ghevar (1 slice)', 70, 'piece', 'sweets', 320, 3.5, 42, 15.5, 0.5, 32, 45, 0.92),
('dates', 'Medjool Dates / Khajoor (2 dates)', 48, 'piece', 'fruits_veg', 133, 0.9, 36, 0.1, 3.2, 32, 1, 0.97),
('anjeer', 'Dried Figs / Anjeer (2 pieces)', 40, 'piece', 'fruits_veg', 100, 1.3, 26, 0.4, 3.8, 19, 4, 0.97),
('pistachios', 'Roasted Salted Pistachios (Pista)', 28, 'fistful', 'dairy_protein', 160, 6, 8, 13, 3, 2, 120, 0.97),
('raisins', 'Golden Raisins / Kishmish', 15, 'tbsp', 'fruits_veg', 45, 0.5, 11.8, 0.1, 0.6, 9.8, 2, 0.98),
('hummus', 'Creamy Chickpea Tahini Hummus', 30, 'tbsp', 'global', 75, 2.4, 4.5, 5.2, 1.8, 0.3, 115, 0.96),
('falafel', 'Crispy Chickpea Falafel Balls (3 pcs)', 75, 'plate', 'global', 210, 6.5, 24, 10.5, 4, 1.8, 290, 0.95),
('pita_bread', 'Whole Wheat Pita Pocket Bread', 60, 'piece', 'global', 165, 5.5, 33, 1, 4, 1.5, 280, 0.96),
('protein_bar', 'Whey Protein Crunch Bar (20g Protein)', 60, 'piece', 'dairy_protein', 210, 20, 22, 6.5, 8, 2, 160, 0.97),
('rice_cakes', 'Puffed Brown Rice Cakes (2 cakes)', 18, 'piece', 'global', 70, 1.5, 14.5, 0.5, 0.8, 0.1, 35, 0.97),
('tuna_salad', 'Canned Chunk Light Tuna in Olive Oil', 140, 'bowl', 'non_veg', 220, 32, 0, 10, 0, 0, 340, 0.96),
('edamame', 'Steamed Edamame Pods with Sea Salt', 150, 'bowl', 'fruits_veg', 180, 17, 14, 8, 8, 3, 220, 0.96),
('custard_apple', 'Fresh Custard Apple / Sitaphal', 130, 'piece', 'fruits_veg', 120, 2.2, 29, 0.4, 4.4, 22, 4, 0.95),
('amla', 'Fresh Indian Gooseberry / Amla (2 pcs)', 50, 'piece', 'fruits_veg', 22, 0.4, 5, 0.1, 2.2, 2, 1, 0.98),
('jamun', 'Fresh Black Jamun / Black Plum (1 cup)', 100, 'cup', 'fruits_veg', 60, 0.7, 14, 0.2, 0.9, 12, 14, 0.96),
('lychee', 'Fresh Lychee / Litchi (6 fruits)', 60, 'piece', 'fruits_veg', 40, 0.5, 10, 0.2, 0.8, 9.2, 1, 0.97),
('arbi_fry', 'Arbi Masala Fry (Colocasia / Taro Root)', 120, 'katori', 'curries', 160, 2, 24, 7, 4.5, 1, 210, 0.93),
('karela_fry', 'Crispy Karela / Bitter Gourd Chips', 80, 'plate', 'curries', 120, 2.2, 12, 7.5, 3.5, 1, 190, 0.93),
('kundru_sabzi', 'Kundru / Ivy Gourd Stir-Fry with Mustard', 120, 'katori', 'curries', 95, 1.8, 10, 5.5, 3.2, 1.5, 170, 0.94),
('gawar_phali', 'Gawar Phali (Cluster Beans) with Ajwain', 120, 'katori', 'curries', 85, 3.5, 11, 3.5, 5, 1.2, 160, 0.94),
('parwal_sabzi', 'Parwal Aloo (Pointed Gourd Potato Sabzi)', 130, 'katori', 'curries', 120, 2.5, 16, 5.5, 3.8, 1.5, 190, 0.93),
('tinda_sabzi', 'Tinda / Apple Gourd Homestyle Masala', 130, 'katori', 'curries', 85, 1.5, 10, 4.5, 2.8, 2, 160, 0.94),
('drumstick_curry', 'Sahjan / Drumstick Curry with Mustard', 150, 'katori', 'curries', 110, 3.8, 13, 5, 4.2, 2, 210, 0.93),
('methi_matar_malai', 'Methi Matar Malai in Creamy Gravy', 160, 'katori', 'curries', 270, 6.5, 18, 19.5, 4, 4, 320, 0.93),
('paneer_lababdar', 'Paneer Lababdar in Rich Tomato Gravy', 160, 'katori', 'curries', 320, 13.5, 11, 25, 2.2, 4.5, 390, 0.93),
('millet_khichdi', 'Foxtail / Bajra Millet Vegetable Khichdi', 220, 'bowl', 'staples', 230, 7, 38, 6, 6.2, 1.2, 260, 0.94),
('ragi_mudde', 'Karnataka Ragi Mudde (Steamed Millet Ball)', 150, 'piece', 'south_indian', 220, 5.2, 46, 1.8, 7.5, 0.4, 45, 0.95),
('kokum_sharbat', 'Kokum Sharbat (Goan Cooling Drink)', 200, 'glass', 'beverages', 60, 0.2, 15, 0, 0.5, 14, 85, 0.96),
('jaljeera', 'Refreshing Spicy Jaljeera Mint Drink', 200, 'glass', 'beverages', 35, 0.8, 8, 0.2, 1.2, 3.5, 260, 0.97),
('bel_sharbat', 'Bel / Wood Apple Fruit Sharbat', 250, 'glass', 'beverages', 140, 1.8, 34, 0.4, 3.5, 28, 35, 0.95),
('thandai', 'Kesar Badam Thandai with Poppy Seeds', 200, 'glass', 'beverages', 210, 6.5, 26, 9.5, 1.8, 22, 80, 0.94)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  estimated_grams = EXCLUDED.estimated_grams,
  serving_unit = EXCLUDED.serving_unit,
  category = EXCLUDED.category,
  calories = EXCLUDED.calories,
  protein = EXCLUDED.protein,
  carbs = EXCLUDED.carbs,
  fat = EXCLUDED.fat,
  fiber = EXCLUDED.fiber,
  sugar = EXCLUDED.sugar,
  sodium = EXCLUDED.sodium,
  confidence = EXCLUDED.confidence;

-- ==============================================================================
-- SEED DATA: INITIAL MASTER SYNC ENCLAVE
-- ==============================================================================
INSERT INTO public.sync_enclaves (sync_code, devices, last_mutation)
VALUES ('CQ-8420-9173', '[{"id":"host","name":"Primary Web Enclave","platform":"web","connectedAt":1790672275062,"lastActive":1790672275062}]'::jsonb, '{"type":"init","details":"Master Enclave CQ-8420-9173 ready","deviceId":"host","timestamp":1790672275062}'::jsonb)
ON CONFLICT (sync_code) DO NOTHING;

-- Schema initialization complete
