const fs = require('fs');
const path = require('path');

// Extract FOOD_NUTRITION_DB from server.js
const serverJsContent = fs.readFileSync(path.join(__dirname, '../server.js'), 'utf8');
const match = serverJsContent.match(/const FOOD_NUTRITION_DB = ({[\s\S]*?^};)/m);
if (!match) {
  console.error('Could not find FOOD_NUTRITION_DB in server.js');
  process.exit(1);
}

// Evaluate FOOD_NUTRITION_DB safely
let foodDb;
try {
  const code = match[0] + '\nmodule.exports = FOOD_NUTRITION_DB;';
  const tmpModule = { exports: {} };
  const fn = new Function('module', 'exports', code);
  fn(tmpModule, tmpModule.exports);
  foodDb = tmpModule.exports;
} catch (e) {
  console.error('Failed to parse FOOD_NUTRITION_DB:', e);
  process.exit(1);
}

const foodKeys = Object.keys(foodDb);
console.log(`Loaded ${foodKeys.length} food items from FOOD_NUTRITION_DB.`);

let sql = `-- ==============================================================================
-- CALORIQ PRODUCTION DATABASE SCHEMA FOR SUPABASE (POSTGRESQL 15+)
-- Project URL: https://tyojindpzxlpbjogsglv.supabase.co
-- Generated: ${new Date().toISOString()}
-- Architecture: Multi-tenant, Multi-device Enclave Sync, Realtime Telemetry, Food Diary
-- ==============================================================================

-- 1. Enable Required Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- TABLE 1: sync_enclaves (Inter-device Enclave Coordination & QR Pairings)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.sync_enclaves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_code TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    last_updated TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    devices JSONB NOT NULL DEFAULT '[]'::jsonb,
    last_mutation JSONB NOT NULL DEFAULT '{"type":"init","details":"Enclave created"}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_sync_enclaves_code ON public.sync_enclaves (sync_code);

-- ==============================================================================
-- TABLE 2: user_profiles (Biometric Targets, Asian Indian BMI, BMR, TDEE)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    sync_code TEXT NOT NULL DEFAULT 'CQ-8420-9173',
    age INT NOT NULL DEFAULT 28,
    sex TEXT NOT NULL DEFAULT 'female' CHECK (sex IN ('female', 'male', 'other')),
    height_cm NUMERIC(5,1) NOT NULL DEFAULT 168.0,
    weight_kg NUMERIC(5,1) NOT NULL DEFAULT 68.0,
    activity_level TEXT NOT NULL DEFAULT 'moderate',
    goal TEXT NOT NULL DEFAULT 'lose' CHECK (goal IN ('lose', 'maintain', 'gain')),
    target_rate_kg_per_week NUMERIC(4,2) NOT NULL DEFAULT 0.50,
    bmr INT NOT NULL DEFAULT 1419,
    tdee INT NOT NULL DEFAULT 2200,
    daily_calorie_target INT NOT NULL DEFAULT 1650,
    protein_target_g INT NOT NULL DEFAULT 122,
    carbs_target_g INT NOT NULL DEFAULT 173,
    fat_target_g INT NOT NULL DEFAULT 51,
    fiber_target_g INT NOT NULL DEFAULT 28,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_user_profiles_sync UNIQUE (sync_code)
);

CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON public.user_profiles (user_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_sync_code ON public.user_profiles (sync_code);

-- ==============================================================================
-- TABLE 3: food_entries (Daily Nutrition Log, Spreadsheet Diary, Macro Breakdown)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.food_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    sync_code TEXT NOT NULL DEFAULT 'CQ-8420-9173',
    device_id TEXT,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    time TEXT NOT NULL DEFAULT to_char(timezone('utc'::text, now()), 'HH12:MI AM'),
    meal_type TEXT NOT NULL CHECK (meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')),
    food_name TEXT NOT NULL,
    quantity NUMERIC(8,2) NOT NULL DEFAULT 100,
    quantity_unit TEXT NOT NULL DEFAULT 'g',
    calories NUMERIC(8,2) NOT NULL DEFAULT 0,
    protein NUMERIC(8,2) NOT NULL DEFAULT 0,
    carbs NUMERIC(8,2) NOT NULL DEFAULT 0,
    fat NUMERIC(8,2) NOT NULL DEFAULT 0,
    fiber NUMERIC(8,2) NOT NULL DEFAULT 0,
    sugar NUMERIC(8,2) NOT NULL DEFAULT 0,
    sodium NUMERIC(8,2) NOT NULL DEFAULT 0,
    source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'ai', 'catalog', 'voice')),
    confidence NUMERIC(4,3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_food_entries_sync_date ON public.food_entries (sync_code, date);
CREATE INDEX IF NOT EXISTS idx_food_entries_user_date ON public.food_entries (user_id, date);
CREATE INDEX IF NOT EXISTS idx_food_entries_created_at ON public.food_entries (created_at DESC);

-- ==============================================================================
-- TABLE 4: weight_logs (Weight History & Asian Indian BMI Progression)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.weight_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    sync_code TEXT NOT NULL DEFAULT 'CQ-8420-9173',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    weight_kg NUMERIC(5,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_weight_logs_sync_date ON public.weight_logs (sync_code, date DESC);
CREATE INDEX IF NOT EXISTS idx_weight_logs_user_date ON public.weight_logs (user_id, date DESC);

-- ==============================================================================
-- TABLE 5: trackers_state (Water Hydration, Sleep Debt, Handwash, Wearables)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.trackers_state (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sync_code TEXT NOT NULL DEFAULT 'CQ-8420-9173',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    water_current_ml INT NOT NULL DEFAULT 0,
    water_target_ml INT NOT NULL DEFAULT 3000,
    water_hourly_log JSONB NOT NULL DEFAULT '[]'::jsonb,
    sleep_duration_hours NUMERIC(4,2) NOT NULL DEFAULT 0,
    sleep_target_hours NUMERIC(4,2) NOT NULL DEFAULT 8.0,
    sleep_quality TEXT NOT NULL DEFAULT 'None',
    sleep_debt_minutes INT NOT NULL DEFAULT 0,
    handwash_count_today INT NOT NULL DEFAULT 0,
    handwash_target_count INT NOT NULL DEFAULT 6,
    handwash_streak_days INT NOT NULL DEFAULT 0,
    fitbit_connected BOOLEAN NOT NULL DEFAULT false,
    fitbit_device TEXT NOT NULL DEFAULT 'None',
    wearables_steps INT NOT NULL DEFAULT 0,
    wearables_active_minutes INT NOT NULL DEFAULT 0,
    wearables_heart_rate INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_trackers_sync_date UNIQUE (sync_code, date)
);

CREATE INDEX IF NOT EXISTS idx_trackers_state_sync_date ON public.trackers_state (sync_code, date DESC);

-- ==============================================================================
-- TABLE 6: health_connect_telemetry (Steps, Active Energy, Basal Burn, Audit Logs)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.health_connect_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_code TEXT NOT NULL DEFAULT 'CQ-8420-9173',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    steps INT NOT NULL DEFAULT 0,
    active_calories INT NOT NULL DEFAULT 0,
    basal_calories INT NOT NULL DEFAULT 1419,
    total_calories INT NOT NULL DEFAULT 1419,
    nutrition_records_count INT NOT NULL DEFAULT 0,
    is_estimated BOOLEAN NOT NULL DEFAULT true,
    hourly_data JSONB NOT NULL DEFAULT '[]'::jsonb,
    sync_audit_log JSONB NOT NULL DEFAULT '[]'::jsonb,
    last_synced_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_health_connect_sync_date UNIQUE (sync_code, date)
);

CREATE INDEX IF NOT EXISTS idx_health_connect_sync_date ON public.health_connect_telemetry (sync_code, date DESC);

-- ==============================================================================
-- TABLE 7: indian_food_catalog (Authentic Indian Serving Sizes & Macronutrients)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.indian_food_catalog (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    estimated_grams NUMERIC(8,2) NOT NULL,
    serving_unit TEXT NOT NULL,
    category TEXT NOT NULL,
    calories NUMERIC(8,2) NOT NULL,
    protein NUMERIC(8,2) NOT NULL,
    carbs NUMERIC(8,2) NOT NULL,
    fat NUMERIC(8,2) NOT NULL,
    fiber NUMERIC(8,2) NOT NULL DEFAULT 0,
    sugar NUMERIC(8,2) NOT NULL DEFAULT 0,
    sodium NUMERIC(8,2) NOT NULL DEFAULT 0,
    confidence NUMERIC(4,3) NOT NULL DEFAULT 0.95,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_indian_food_category ON public.indian_food_catalog (category);
CREATE INDEX IF NOT EXISTS idx_indian_food_name ON public.indian_food_catalog (name);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE public.sync_enclaves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.food_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weight_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trackers_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_connect_telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.indian_food_catalog ENABLE ROW LEVEL SECURITY;

-- 1. sync_enclaves Policies
CREATE POLICY "Allow public read-write for active sync enclaves" 
ON public.sync_enclaves FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- 2. user_profiles Policies
CREATE POLICY "Allow public read-write user profiles by sync_code or auth" 
ON public.user_profiles FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- 3. food_entries Policies
CREATE POLICY "Allow public read-write food entries by sync_code or auth" 
ON public.food_entries FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- 4. weight_logs Policies
CREATE POLICY "Allow public read-write weight logs by sync_code or auth" 
ON public.weight_logs FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- 5. trackers_state Policies
CREATE POLICY "Allow public read-write trackers state by sync_code or auth" 
ON public.trackers_state FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- 6. health_connect_telemetry Policies
CREATE POLICY "Allow public read-write health connect telemetry by sync_code" 
ON public.health_connect_telemetry FOR ALL TO anon, authenticated 
USING (true) WITH CHECK (true);

-- 7. indian_food_catalog Policies (Publicly readable, service_role writable)
CREATE POLICY "Allow public read access to Indian food catalog" 
ON public.indian_food_catalog FOR SELECT TO anon, authenticated 
USING (true);

CREATE POLICY "Allow service_role write access to Indian food catalog" 
ON public.indian_food_catalog FOR ALL TO service_role 
USING (true) WITH CHECK (true);

-- ==============================================================================
-- PERMISSIONS & ROLES
-- ==============================================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

-- ==============================================================================
-- ENABLE SUPABASE REALTIME REPLICATION FOR INSTANT MULTI-DEVICE SYNC
-- ==============================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END $$;

ALTER PUBLICATION supabase_realtime ADD TABLE public.food_entries;
ALTER PUBLICATION supabase_realtime ADD TABLE public.trackers_state;
ALTER PUBLICATION supabase_realtime ADD TABLE public.sync_enclaves;
ALTER PUBLICATION supabase_realtime ADD TABLE public.user_profiles;
ALTER PUBLICATION supabase_realtime ADD TABLE public.weight_logs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.health_connect_telemetry;

-- ==============================================================================
-- SEED DATA: 250+ AUTHENTIC INDIAN & GLOBAL FOODS WITH AUTHENTIC MACROS
-- ==============================================================================
`;

// Build batch inserts for indian_food_catalog
const valueRows = [];
for (const [key, item] of Object.entries(foodDb)) {
  const safeId = key.replace(/'/g, "''");
  const safeName = (item.name || key).replace(/'/g, "''");
  const grams = parseFloat(item.estimated_grams) || 100;
  const unit = (item.serving_unit || 'serving').replace(/'/g, "''");
  const cat = (item.category || 'general').replace(/'/g, "''");
  const cal = parseFloat(item.calories) || 0;
  const p = parseFloat(item.protein) || 0;
  const c = parseFloat(item.carbs) || 0;
  const f = parseFloat(item.fat) || 0;
  const fib = parseFloat(item.fiber) || 0;
  const sug = parseFloat(item.sugar) || 0;
  const sod = parseFloat(item.sodium) || 0;
  const conf = parseFloat(item.confidence) || 0.95;

  valueRows.push(`('${safeId}', '${safeName}', ${grams}, '${unit}', '${cat}', ${cal}, ${p}, ${c}, ${f}, ${fib}, ${sug}, ${sod}, ${conf})`);
}

sql += `INSERT INTO public.indian_food_catalog (id, name, estimated_grams, serving_unit, category, calories, protein, carbs, fat, fiber, sugar, sodium, confidence)
VALUES
${valueRows.join(',\n')}
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  estimated_grams = EXCLUDED.estimated_grams,
  serving_unit = EXCLUDED.serving_unit,
  category = EXCLUDED.category,
  calories = EXCLUDED.calories,
  protein = EXCLUDED.protein,
  carbs = EXCLUDED.carbs,
  fat = EXCLUDED.fat,
  fiber = EXCLUDED.fiber,
  sugar = EXCLUDED.sugar,
  sodium = EXCLUDED.sodium,
  confidence = EXCLUDED.confidence;

-- ==============================================================================
-- SEED DATA: INITIAL MASTER SYNC ENCLAVE
-- ==============================================================================
INSERT INTO public.sync_enclaves (sync_code, devices, last_mutation)
VALUES ('CQ-8420-9173', '[{"id":"host","name":"Primary Web Enclave","platform":"web","connectedAt":${Date.now()},"lastActive":${Date.now()}}]'::jsonb, '{"type":"init","details":"Master Enclave CQ-8420-9173 ready","deviceId":"host","timestamp":${Date.now()}}'::jsonb)
ON CONFLICT (sync_code) DO NOTHING;

-- Schema initialization complete
`;

const outputPath = path.join(__dirname, '../supabase_schema.sql');
fs.writeFileSync(outputPath, sql, 'utf8');
console.log(`Generated ${outputPath} (${(sql.length / 1024).toFixed(1)} KB) with ${valueRows.length} food items.`);
